CREATE TABLE IF NOT EXISTS `CURRENCY`(
    `ID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `CODE` VARCHAR(3) NOT NULL DEFAULT '',
    `CHINESE_NAME` VARCHAR(20) NOT NULL DEFAULT '',
    `DESCRIPTION` VARCHAR(255),
    `CREATE_TIME` DATETIME NOT NULL DEFAULT NOW(),
    `UPDATE_TIME` DATETIME NOT NULL DEFAULT NOW()
);

INSERT INTO CURRENCY (ID, CODE, CHINESE_NAME, DESCRIPTION, CREATE_TIME, UPDATE_TIME)
VALUES(1, 'USD', '美元', '', NOW(), NOW()),
(2, 'GBP', '英鎊', '', NOW(), NOW()),
(3, 'EUR', '歐元', '', NOW(), NOW());

alter sequence hibernate_sequence restart with 4;