CREATE TABLE IF NOT EXISTS `CURRENCY`(
    `ID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(20) NOT NULL DEFAULT '',
    `CODE` VARCHAR(3) NOT NULL DEFAULT '',
    `SYMBOL` VARCHAR(10) NOT NULL DEFAULT '',
    `DESCRIPTION` VARCHAR(255),
    `RATE` DECFLOAT(10) NOT NULL DEFAULT 1,
    `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);